### PR TITLE
CI cache test

### PR DESCRIPTION
**Pull request by xzandrew**

### CODE REVIEW

**Comment by jhaynie** [comment]
once you figure this out, let the rest of us know lol!

**Comment by xzandrew** [comment]
@jhaynie The code here is supposed to reuse GOPATH/pkg (/codefresh/volume/go) which also includes dep cache, but it doesn't work for some reason. We couldn't figure this out with Robin.

**Comment by josecordaz** [comment]
Hey guys. The place where Go saves unit tests cache inside a container is in /root/.cache 😄 . You can run a quick test using [this](https://github.com/josecordaz/unit_tests_go_docker). I hope this can give some light in what you guys are doing.

**Comment by xzandrew** [comment]
@josecordaz Thanks, will take a look.

**Pull request closed without merging**
