### PR TITLE
APP-2853 Sonarqube refactor

### PR DESCRIPTION
**Pull request by josecordaz**
**WIP**

### CODE REVIEW

**Comment by pec1985** [comment]
I don't understand the purpose of this refactor. Are there any bugs fixed here?

**Comment by josecordaz** [comment]
> I don't understand the purpose of this refactor. Are there any bugs fixed here?

No bugs, only trying to apply the same structure we have in other integrations.

**Comment by xzandrew** [comment]
It's nice to make it similar to other integrations, but with the new code we are now missing http request retries that were here before.

**Comment by josecordaz** [comment]
> It's nice to make it similar to other integrations, but with the new code we are now missing http request retries that were here before.

yes, will work on that

**Comment by xzandrew** [comment]
This is very low priority.

**Pull request closed without merging**
